[project]
name = "mlflow-wine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow[extras]>=2.22.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
